### ISSUE TITLE
async script

### ISSUE THREAD

**Issue by yoshuawuyts** [sethvincent/create-html#4]
Would be cool if there was an option to let the script load async, so instead of appending it to the `<body>` we could just let it sit in the `<head>`. https://github.com/sethvincent/create-html/blob/master/index.js#L22

This would allow us to ditch `nanomount` in `choo` and allow for faster rendering / faster time for dom ready / smaller bundles. Thanks!

## See Also
- http://caniuse.com/#feat=script-async
- https://developer.mozilla.org/en/HTML/Element/script#Attributes

**Comment by sethvincent** [comment]
Cool. How about a `--script-async` / `scriptAsync` option?

**Comment by yoshuawuyts** [comment]
Yeah sounds great!

**Comment by sethvincent** [comment]
I might not have time to implement this right away, but hey, it would be a good beginner issue!

How I'd implement it:

- create an option named `scriptAsync` in the JS API
- create a flag called `--script-async` in the CLI API
- the script tag will have the [`async` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-async)
- the script will be placed in the `head` instead of the body.
- add references to this option to the README and CLI help output

**Comment by sethvincent** [comment]
closed by #6 🎉 

thanks @rreusser!
